library synth;
context synth.synth_context;

-- Parallel RGB interface for GateMate FPGAs by Cologne Chip
--
-- Converts an AXI Stream of pixel data to parallel RGB signals.
-- Two video modes are supported: 1080p @ 60 Hz and 720p @ 60 Hz
--
-- Please see README.md for confirmed working configurations.

entity parallel_rgb is
    generic (
        PIXELS_PER_CLOCK: integer;                   -- 1 or 2; Must be 2 for 1080p to meet timing
        VIDEO_MODE: string;                         -- 1080p or 720p
        PERF_MODE: string;                          -- FPGA performance mode
        REF_CLK_FREQ: string;                       -- Frequency of reference clock in MHz
        INVERT_SYNCS: boolean := false;             -- Invert sync signals if true
        INVERT_RGB_CLK: boolean := false;           -- Inverts rgb_clk if true
        DIFF_RGB_CLK: boolean := true;              -- Choose between differential and single ended clock output
        PIXEL_BUS_WIDTH: integer := 24;             -- 12 or 24; if 12 then DDR output will be used (reqires PIXELS_PER_CLOCK=2)

        -- Optional signals for differential clock output
        DIFF_CLK_PIN_NAME_P: string := "UNPLACED";  -- IO_<Dir><Bank>_<Pin><Pin#>
        DIFF_CLK_PIN_NAME_N: string := "UNPLACED";  -- secondary diff. signal
        DIFF_CLK_V_IO      : string := "UNDEFINED"  -- "1.8" or "2.5" Volt
    );
    port (
        -- Reference input clock
        ref_clk: in std_ulogic;

        -- Async reset signal
        usr_reset_n: in std_ulogic;

        -- Parallel RGB output signals
        rgb_clk_p: out std_ulogic;
        rgb_clk_n: out std_ulogic; -- Not used if DIFF_RGB_CLK=false
        rgb_data: out std_ulogic_vector(PIXEL_BUS_WIDTH-1 downto 0);
        rgb_de: out std_ulogic;
        rgb_hsync: out std_ulogic;
        rgb_vsync: out std_ulogic;

        -- Pixel clock is generated by the entity
        pixel_clk: out std_ulogic;

        -- Input pixel data streamed by AXI Stream. TVALID may only be '0'
        -- during blanking periods!
        pixel_tdata: in std_ulogic_vector(PIXELS_PER_CLOCK*24-1 downto 0);
        pixel_tvalid: in std_ulogic;
        pixel_tready: out std_ulogic;

        -- Synchronization signals for data source.
        -- EOL will be asserted immedeately after receiving the last pixel of a row
        -- EOF will be asserted after a some delay
        pixel_eol: out std_ulogic;
        pixel_eof: out std_ulogic
    );
end parallel_rgb;

architecture rtl of parallel_rgb is
    -- Required component declarations
    component CC_PLL is
            generic (
            REF_CLK         : string := "0.0";  -- reference input in MHz
            OUT_CLK         : string := "0.0";  -- pll output frequency in MHz
            PERF_MD         : string := "UNDEFINED";  -- LOWPOWER, ECONOMY, SPEED
            LOW_JITTER      : integer := 1; -- 0: disable, 1: enable low jitter mode
            LOCK_REQ        : integer := 1; -- Lock status required before PLL output enable
            CLK270_DOUB     : integer := 0; -- Frequency doubling of CLOCK_270 PLL output
            CLK180_DOUB     : integer := 0; -- Frequency doubling of CLOCK_180 PLL output
            CI_FILTER_CONST : integer := 2; -- optional CI filter constant
            CP_FILTER_CONST : integer := 2  -- optional CP filter constant
        );
        port (
            CLK_REF             : in  std_ulogic;
            USR_CLK_REF         : in  std_ulogic;
            CLK_FEEDBACK        : in  std_ulogic;
            USR_LOCKED_STDY_RST : in  std_ulogic;
            USR_PLL_LOCKED_STDY : out std_ulogic;
            USR_PLL_LOCKED      : out std_ulogic;
            CLK0                : out std_ulogic;
            CLK90               : out std_ulogic;
            CLK180              : out std_ulogic;
            CLK270              : out std_ulogic;
            CLK_REF_OUT         : out std_ulogic
        );
    end component;

    component rgb_output_stage is
        generic (
            PIXELS_PER_CLOCK: integer;                   -- 1 or 2; Must be 2 for 1080p to meet timing
            INVERT_RGB_CLK: boolean := false;           -- Inverts rgb_clk if true
            DIFF_RGB_CLK: boolean := true;              -- Choose between differential and single ended clock output
            PIXEL_BUS_WIDTH: integer := 24;             -- 12 or 24; if 12 then DDR output will be used (reqires PIXELS_PER_CLOCK=2)

            -- Optional signals for differential clock output
            DIFF_CLK_PIN_NAME_P: string := "UNPLACED";  -- IO_<Dir><Bank>_<Pin><Pin#>
            DIFF_CLK_PIN_NAME_N: string := "UNPLACED";  -- secondary diff. signal
            DIFF_CLK_V_IO      : string := "UNDEFINED"  -- "1.8" or "2.5" Volt
        );
        port (
            -- Parallel RGB output signals
            rgb_clk_p: out std_ulogic;
            rgb_clk_n: out std_ulogic; -- Not used if DIFF_RGB_CLK=false
            rgb_data: out std_ulogic_vector(PIXEL_BUS_WIDTH-1 downto 0);
            rgb_de: out std_ulogic;
            rgb_hsync: out std_ulogic;
            rgb_vsync: out std_ulogic;

            -- Input signals
            input_data_clk: in std_ulogic;
            input_rgb_clk: in std_ulogic;
            input_de: in std_ulogic;
            input_hsync: in std_ulogic;
            input_vsync: in std_ulogic;
            input_data: in std_ulogic_vector(PIXELS_PER_CLOCK*24-1 downto 0)
        );
    end component;

    -- For video timing parameters please see:
    -- https://tomverbeure.github.io/video_timings_calculator
    -- We are using either 720p CVT-RB or 1080p CEA-861
    constant PIXEL_CLOCK: real := select_constant(VIDEO_MODE = "720p", 64.0, 148.5); --MHz
    constant SCREEN_WIDTH: integer := select_constant(VIDEO_MODE = "720p", 1280, 1920);
    constant SCREEN_HEIGHT: integer := select_constant(VIDEO_MODE = "720p", 720, 1080);
    constant HORIZONTAL_FRONT_PORCH: integer := select_constant(VIDEO_MODE = "720p", 48, 88);
    constant HSYNC_LEN: integer := select_constant(VIDEO_MODE = "720p", 32, 44);
    constant HORIZONTAL_BACK_PORCH: integer := select_constant(VIDEO_MODE = "720p", 80, 148);
    constant VERTICAL_FRONT_PORCH: integer := select_constant(VIDEO_MODE = "720p", 3, 4);
    constant VSYNC_LEN: integer := 5;
    constant VERTICAL_BACK_PORCH: integer := select_constant(VIDEO_MODE = "720p", 13, 36);

    constant SYNC_XOR: std_ulogic := select_constant(INVERT_SYNCS, '1', '0');

    -- Clocking
    signal rgb_clk: std_ulogic;

    -- State counters
    signal x: unsigned(log2(SCREEN_WIDTH/PIXELS_PER_CLOCK)-1 downto 0);
    signal y: unsigned(log2(SCREEN_HEIGHT)-1 downto 0);
    signal hporch_counter: unsigned(log2(maximum(HORIZONTAL_FRONT_PORCH, HORIZONTAL_BACK_PORCH)/PIXELS_PER_CLOCK)-1 downto 0);
    signal vporch_counter: unsigned(log2(maximum(VERTICAL_FRONT_PORCH, VERTICAL_BACK_PORCH))-1 downto 0);
    signal hsync_counter: unsigned(log2(HSYNC_LEN/PIXELS_PER_CLOCK)-1 downto 0);
    signal vsync_counter: unsigned(log2(VSYNC_LEN+1)-1 downto 0);

    -- Front / backporch states
    signal hfp_active: std_ulogic;
    signal hbp_active: std_ulogic;
    signal vfp_active: std_ulogic;
    signal vbp_active: std_ulogic;

    signal vsync_active: std_ulogic;
    signal hsync_active: std_ulogic;

    signal internal_hsync: std_ulogic;
    signal internal_vsync: std_ulogic;
    signal internal_de: std_ulogic;
    signal internal_rgb_data: std_ulogic_vector(PIXELS_PER_CLOCK*24 - 1 downto 0);

    signal row_ready: std_ulogic;
begin
    assert PIXELS_PER_CLOCK = 1 or PIXELS_PER_CLOCK = 2 severity failure;
    assert VIDEO_MODE = "1080p" or VIDEO_MODE = "720p" severity failure;

    -- Generate main clock through PLL
    pll: component CC_PLL
        generic map (
            REF_CLK         => REF_CLK_FREQ,
            OUT_CLK         => to_string(PIXEL_CLOCK / real(PIXELS_PER_CLOCK)),
            PERF_MD         => PERF_MODE,
            LOW_JITTER      => 1,
            CLK180_DOUB     => select_constant(PIXELS_PER_CLOCK = 2, 1, 0)
        )
        port map (
            CLK_REF             => ref_clk,
            USR_CLK_REF         => '0',
            CLK_FEEDBACK        => '0',
            USR_LOCKED_STDY_RST => '0',
            USR_PLL_LOCKED_STDY => open,
            USR_PLL_LOCKED      => open,
            CLK0                => pixel_clk,
            CLK90               => open,
            CLK180              => rgb_clk,
            CLK270              => open,
            CLK_REF_OUT         => open
        );

    -- The physical output stage is encapsulated in a separate component
    output_stage: component rgb_output_stage
        generic map (
            PIXELS_PER_CLOCK     => PIXELS_PER_CLOCK,
            INVERT_RGB_CLK      => INVERT_RGB_CLK,
            DIFF_RGB_CLK        => DIFF_RGB_CLK,
            DIFF_CLK_PIN_NAME_P => DIFF_CLK_PIN_NAME_P,
            DIFF_CLK_PIN_NAME_N => DIFF_CLK_PIN_NAME_N,
            DIFF_CLK_V_IO       => DIFF_CLK_V_IO,
            PIXEL_BUS_WIDTH     => PIXEL_BUS_WIDTH
        )
        port map (
            rgb_clk_p       => rgb_clk_p,
            rgb_clk_n       => rgb_clk_n,
            rgb_data        => rgb_data,
            rgb_de          => rgb_de,
            rgb_hsync       => rgb_hsync,
            rgb_vsync       => rgb_vsync,
            input_data_clk  => pixel_clk,
            input_rgb_clk   => rgb_clk,
            input_de        => internal_de,
            input_hsync     => internal_hsync,
            input_vsync     => internal_vsync,
            input_data      => internal_rgb_data
        );

    -- Generate Parallel RGB signals
    process(pixel_clk, usr_reset_n)
    begin
        if usr_reset_n = '0' then
            x <= (others => '0');
            y <= (others => '0');

            vsync_counter <= (others => '0');
            hsync_counter <= (others => '0');

            hporch_counter <= (others => '0');
            vporch_counter <= (others => '0');

            vsync_active <= '1'; -- Start with vsync
            hsync_active <= '1'; -- Start with hsync
            hfp_active <= '0';
            hbp_active <= '0';
            vfp_active <= '0';
            vbp_active <= '0';

            internal_hsync <= '0' xor SYNC_XOR;
            internal_vsync <= '0' xor SYNC_XOR;
            internal_de <= '0';
            internal_rgb_data <= (others => '0');

            pixel_eol <= '0';
            pixel_eof <= '0';

            pixel_tready <= '0';
            row_ready <= '1';
        elsif rising_edge(pixel_clk) then
            -- Receive new pixel from AXI stream
            if pixel_tready = '1' then
                assert pixel_tvalid = '1' severity failure;
                internal_de <= '1';
                internal_rgb_data <=  pixel_tdata;
            else
                internal_de <= '0';
                internal_rgb_data <=  (others => '0'); -- Don't put out data during blanking
            end if;

            -- Increment x coordinate
            if (pixel_tready = '1' and pixel_tvalid = '1') or row_ready = '1' then
                if x /= SCREEN_WIDTH/PIXELS_PER_CLOCK-1 then
                    x <= x + 1;
                else
                    -- Reached end of line
                    hfp_active <= '1';
                    pixel_tready <= '0';
                    row_ready <= '0';
                    if vsync_active = '0' and vfp_active = '0' and vbp_active = '0' then
                        pixel_eol <= '1';
                    end if;
                    x <= (others => '0');
                end if;
            end if;

            -- Increment pixel y location at start of hsync
            if hsync_active = '1' and internal_hsync = ('0' xor SYNC_XOR) and vsync_active = '0'
                and vfp_active = '0' and vbp_active = '0'
            then
                if y /= SCREEN_HEIGHT-1 then
                    y <= y + 1;
                else
                    pixel_eof <= '1';
                    vfp_active <= '1';
                    y <= (others => '0');
                end if;
            end if;

            -- Generate vsync
            if vsync_active = '1' then
                if hsync_active = '1' and internal_hsync = ('0' xor SYNC_XOR) then
                    if vsync_counter /= VSYNC_LEN then
                        vsync_counter <= vsync_counter+1;
                        internal_vsync <= '1' xor SYNC_XOR;
                    else
                        vsync_counter <= (others => '0');
                        vsync_active <= '0';
                        vbp_active <= '1';
                        internal_vsync <= '0' xor SYNC_XOR;
                    end if;
                end if;
            end if;

            -- Generate hsync
            if hsync_active = '1' then
                if hsync_counter /= HSYNC_LEN/PIXELS_PER_CLOCK - 1 then
                    hsync_counter <= hsync_counter+1;
                else
                    hsync_counter <= (others => '0');
                    hsync_active <= '0';
                    hbp_active <= '1';
                end if;
            end if;
            internal_hsync <= hsync_active xor SYNC_XOR;

            -- Generate vertical front/back porch
            if (vfp_active = '1' or vbp_active = '1') and (hsync_active = '1' and internal_hsync = ('0' xor SYNC_XOR)) then
                if (vfp_active = '1' and vporch_counter /= VERTICAL_FRONT_PORCH-2) or
                    (vbp_active = '1' and vporch_counter /= VERTICAL_BACK_PORCH-1)
                then
                    vporch_counter <= vporch_counter + 1;
                else
                    vporch_counter <= (others => '0');

                    if vfp_active = '1' then
                        vsync_active <= '1';
                    end if;

                    vfp_active <= '0';
                    vbp_active <= '0';
                end if;
            end if;

            -- Generate horizontal front/back porch
            if hfp_active = '1' or hbp_active = '1' then
                if (hfp_active = '1' and hporch_counter /= HORIZONTAL_FRONT_PORCH/PIXELS_PER_CLOCK-1)
                    or (hbp_active = '1' and hporch_counter /= HORIZONTAL_BACK_PORCH/PIXELS_PER_CLOCK-1)
                then
                    hporch_counter <= hporch_counter + 1;
                else
                    hporch_counter <= (others => '0');

                    if hfp_active = '1' then
                        hsync_active <= '1';
                    end if;
                    if hbp_active = '1' then
                        if vsync_active = '0' and vfp_active = '0' and vbp_active = '0' then
                            pixel_tready <= '1';
                        else
                            pixel_tready <= '0';
                        end if;
                        row_ready <= '1';
                    end if;

                    hfp_active <= '0';
                    hbp_active <= '0';
                end if;
            end if;

            -- Reset EOL/EOF signals
            if pixel_eof = '1' then
                pixel_eof <= '0';
            end if;

            if pixel_eol = '1' then
                pixel_eol <= '0';
            end if;
        end if;
    end process;
end rtl;
