library synth;
context synth.synth_context;

-- Toplevel entitity of the design
entity toplevel is
    port (
        ref_clk: in std_ulogic;
        led: out std_ulogic;

        rgb_clk_p: out std_ulogic;
        rgb_clk_n: out std_ulogic;
        rgb_data: out std_ulogic_vector(23 downto 0);
        rgb_de: out std_ulogic;
        rgb_hsync: out std_ulogic;
        rgb_vsync: out std_ulogic;

        pmod: out std_ulogic_vector(7 downto 0)
    );
end toplevel;

architecture rtl of toplevel is
    component parallel_rgb is
        generic (
            PIXELS_PER_CLOCK: integer;                   -- 1 or 2; Must be 2 for 1080p to meet timing
            VIDEO_MODE: string;                         -- 1080p or 720p
            PERF_MODE: string;                          -- FPGA performance mode
            REF_CLK_FREQ: string;                       -- Frequency of reference clock in MHz
            INVERT_SYNCS: boolean := false;             -- Invert sync signals if true
            INVERT_RGB_CLK: boolean := false;           -- Inverts rgb_clk if true
            DIFF_RGB_CLK: boolean := true;              -- Choose between differential and single ended clock output
            PIXEL_BUS_WIDTH: integer := 24;             -- 12 or 24; if 12 then DDR output will be used (reqires PIXELS_PER_CLOCK=2)

            -- Optional signals for differential clock output
            DIFF_CLK_PIN_NAME_P: string := "UNPLACED";  -- IO_<Dir><Bank>_<Pin><Pin#>
            DIFF_CLK_PIN_NAME_N: string := "UNPLACED";  -- secondary diff. signal
            DIFF_CLK_V_IO      : string := "UNDEFINED"  -- "1.8" or "2.5" Volt
        );
        port (
            -- Reference input clock
            ref_clk: in std_ulogic;

            -- Async reset signal
            usr_reset_n: in std_ulogic;

            -- Parallel RGB output signals
            rgb_clk_p: out std_ulogic;
            rgb_clk_n: out std_ulogic;
            rgb_data: out std_ulogic_vector(PIXEL_BUS_WIDTH-1 downto 0);
            rgb_de: out std_ulogic;
            rgb_hsync: out std_ulogic;
            rgb_vsync: out std_ulogic;

            -- Pixel clock is generated by the entity
            pixel_clk: out std_ulogic;

            -- Input pixel data streamed by AXI Stream
            pixel_tdata: in std_ulogic_vector(PIXELS_PER_CLOCK*24-1 downto 0);
            pixel_tvalid: in std_ulogic;
            pixel_tready: out std_ulogic;
            pixel_eol: out std_ulogic;
            pixel_eof: out std_ulogic
        );
    end component;

    component CC_USR_RSTN is
        port (
            USR_RSTN: out std_ulogic
        );
    end component;

    constant DIFFERENTIAL_CLOCK: boolean := true; -- or false
    constant PIXEL_BUS_WIDTH: integer := 24; -- or 12
    constant PIXELS_PER_CLOCK: integer := 2; -- or 1
    constant VIDEO_MODE: string := "1080p"; -- or "720p"

    constant SCREEN_MAX_WIDTH: integer := 1920;
    constant SCREEN_MAX_HEIGHT: integer := 1080;

    signal usr_reset_n: std_ulogic;

    signal pixel_clk: std_ulogic;
    signal pixel_tdata: std_ulogic_vector(PIXELS_PER_CLOCK*24-1 downto 0);
    signal pixel_tvalid: std_ulogic;
    signal pixel_tready: std_ulogic;
    signal pixel_eol: std_ulogic;
    signal pixel_eof: std_ulogic;

    signal rgb_clk_p_unswapped: std_ulogic;
    signal rgb_clk_n_unswapped: std_ulogic;

    signal x: unsigned(log2(SCREEN_MAX_WIDTH/PIXELS_PER_CLOCK)-1 downto 0);
    signal y: unsigned(log2(SCREEN_MAX_HEIGHT)-1 downto 0);
    signal frame_counter: unsigned(7 downto 0);
    signal prev_frame_counter: unsigned(7 downto 0);
begin
    -- Differential clock pins are swappend on PCB
    rgb_clk_p <= rgb_clk_n_unswapped when DIFFERENTIAL_CLOCK else rgb_clk_p_unswapped;
    rgb_clk_n <= rgb_clk_p_unswapped when DIFFERENTIAL_CLOCK else rgb_clk_n_unswapped;

    -- Unused pins in 12-bit mode
    rgb_data(23 downto PIXEL_BUS_WIDTH) <= (others => '0');

    pmod <= (others => '0');

    -- Componenbt for generating the Parallel RGB signals
    rgb: component parallel_rgb
        generic map (
            REF_CLK_FREQ => "25",
            PERF_MODE => "ECONOMY",
            PIXELS_PER_CLOCK => PIXELS_PER_CLOCK,
            VIDEO_MODE => VIDEO_MODE,
            INVERT_RGB_CLK => DIFFERENTIAL_CLOCK, -- Pins swapped on PCB
            DIFF_RGB_CLK => DIFFERENTIAL_CLOCK,
            PIXEL_BUS_WIDTH => PIXEL_BUS_WIDTH,

            -- Differential pin settings not strictly neccessary
            -- but NEXTPNR does generate a warning if missing
            DIFF_CLK_PIN_NAME_P => "IO_EA_A0",
            DIFF_CLK_PIN_NAME_N => "IO_EA_B0",
            DIFF_CLK_V_IO => "1.8"
        )
        port map (
            ref_clk         => ref_clk,
            usr_reset_n     => usr_reset_n,
            rgb_clk_p       => rgb_clk_p_unswapped,
            rgb_clk_n       => rgb_clk_n_unswapped,
            rgb_data        => rgb_data(PIXEL_BUS_WIDTH-1 downto 0),
            rgb_de          => rgb_de,
            rgb_hsync       => rgb_hsync,
            rgb_vsync       => rgb_vsync,
            pixel_clk       => pixel_clk,
            pixel_tdata     => pixel_tdata,
            pixel_tvalid    => pixel_tvalid,
            pixel_tready    => pixel_tready,
            pixel_eol       => pixel_eol,
            pixel_eof       => pixel_eof
        );

    usr_rstn: component CC_USR_RSTN
        port map (
            USR_RSTN => usr_reset_n
        );

    -- Generate test video data
    process(pixel_clk, usr_reset_n)
    begin
        if usr_reset_n = '0' then
            x <= (others => '0');
            y <= (others => '0');
            pixel_tdata <= (others => '0');
            pixel_tvalid <= '0';
            led <= '0';
            frame_counter <= (others => '0');
            prev_frame_counter <= (others => '0');
        elsif rising_edge(pixel_clk) then
            led <= frame_counter(4);

            if pixel_tready = '1' or pixel_tvalid = '0' then
                -- Output test data
                pixel_tdata(23 downto 0) <= std_ulogic_vector(resize(x*PIXELS_PER_CLOCK, 8) & resize(y+prev_frame_counter, 8)
                    & resize(x*PIXELS_PER_CLOCK+prev_frame_counter, 8));
                if PIXELS_PER_CLOCK > 1 then
                    pixel_tdata(47 downto 24) <= std_ulogic_vector(resize(x*PIXELS_PER_CLOCK+1, 8) & resize(y+prev_frame_counter, 8)
                        & resize(x*PIXELS_PER_CLOCK+frame_counter+1, 8));
                end if;

                pixel_tvalid <= '1';

                -- Keep track of image location
                x <= x + 1;
            end if;

            if pixel_eol = '1' then
                x <= (others => '0');
                y <= y + 1;
                pixel_tvalid <= '0';
            end if;

            -- frame_counter <= (others => '0');
            if pixel_eof = '1' then
                y <= (others => '0');
                x <= (others => '0');
                prev_frame_counter <= frame_counter;
                frame_counter <= frame_counter + 1;
                pixel_tvalid <= '0';
            end if;
        end if;
    end process;
end rtl;
